use irrigacao

INSERT INTO Países (Descrição, [Código do País], Inativo) Values('AFEGANISTAO', 0132, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ALBANIA', 0175, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ALEMANHA', 0230, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BURKINA FASO', 0310, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ANDORRA', 0370, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ANGOLA', 0400, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ANGUILLA', 0418, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ANTIGUA E BARBUDA', 0434, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ANTILHAS HOLANDESAS', 0477, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ARABIA SAUDITA', 0531, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ARGELIA', 0590, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ARGENTINA', 0639, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ARMENIA', 0647, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ARUBA', 0655, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('AUSTRALIA', 0698, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('AUSTRIA', 0728, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('AZERBAIJAO', 0736, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BAHAMAS', 0779, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BAHREIN', 0809, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BANGLADESH', 0817, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BARBADOS', 0833, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BELARUS', 0850, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BELGICA', 0876, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BELIZE', 0884, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BERMUDAS', 0906, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MIANMAR', 0930, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BOLIVIA', 0973, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BOSNIA', 0981, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BOTSUANA', 1015, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BRASIL', 1058, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BRUNEI', 1082, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BULGARIA', 1112, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BURUNDI', 1155, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BUTAO', 1198, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CABO VERDE', 1279, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CAYMAN', 1376, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CAMBOJA', 1414, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CAMAROES', 1457, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CANADA', 1490, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GUERNSEY', 1504, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('JERSEY', 1508, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CANARIAS', 1511, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CAZAQUISTAO', 1538, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CATAR', 1546, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CHILE', 1589, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CHINA', 1600, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('FORMOSA', 1619, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CHIPRE', 1635, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('COCOS (KEELING)', 1651, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('COLOMBIA', 1694, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('COMORES', 1732, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CONGO', 1775, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('COOK', 1830, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('COREIA DO NORTE', 1872, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('COREIA DO SUL', 1902, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('COSTA DO MARFIM', 1937, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CROACIA', 1953, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('COSTA RICA', 1961, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('COVEITE', 1988, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CUBA', 1996, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('BENIN', 2291, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('DINAMARCA', 2321, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('DOMINICA', 2356, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('EQUADOR', 2399, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('EGITO', 2402, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ERITREIA', 2437, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('EMIRADOS ARABES', 2445, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ESPANHA', 2453, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ESLOVENIA', 2461, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ESLOVACA', 2470, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ESTADOS UNIDOS', 2496, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ESTONIA', 2518, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ETIOPIA', 2534, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('FALKLAND', 2550, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('FEROE', 2593, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('FILIPINAS', 2674, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('FINLANDIA', 2712, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('FRANCA', 2755, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GABAO', 2810, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GAMBIA', 2852, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GANA', 2895, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GEORGIA', 2917, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GIBRALTAR', 2933, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GRANADA', 2976, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GRECIA', 3018, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GROENLANDIA', 3050, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GUADALUPE', 3093, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GUAM', 3131, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GUATEMALA', 3174, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GUIANA FRANCESA', 3255, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GUINE', 3298, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GUINE-EQUATORIAL', 3310, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GUINE-BISSAU', 3344, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('GUIANA', 3379, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('HAITI', 3417, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('HONDURAS', 3450, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('HONG KONG', 3514, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('HUNGRIA', 3557, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('IEMEN', 3573, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MAN', 3595, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('INDIA', 3611, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('INDONESIA', 3654, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('IRAQUE', 3697, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('IRA', 3727, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('IRLANDA', 3751, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ISLANDIA', 3794, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ISRAEL', 3832, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ITALIA', 3867, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('JAMAICA', 3913, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('JOHNSTON', 3964, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('JAPAO', 3999, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('JORDANIA', 4030, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('KIRIBATI', 4111, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('LAOS', 4200, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('LEBUAN', 4235, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('LESOTO', 4260, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('LETONIA', 4278, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('LIBANO', 4316, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('LIBERIA', 4340, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('LIBIA', 4383, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('LIECHTENSTEIN', 4405, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('LITUANIA', 4421, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('LUXEMBURGO', 4456, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MACAU', 4472, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MACEDONIA', 4499, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MADAGASCAR', 4502, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MADEIRA', 4525, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MALASIA', 4553, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MALAVI', 4588, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MALDIVAS', 4618, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MALI', 4642, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MALTA', 4677, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MARIANAS DO NORTE', 4723, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MARROCOS', 4740, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MARSHALL', 4766, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MARTINICA', 4774, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MAURICIO', 4855, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MAURITANIA', 4880, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MAYOTTE', 4885, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MIDWAY', 4901, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MEXICO', 4936, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MOLDAVIA', 4944, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MONACO', 4952, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MONGOLIA', 4979, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MONTENEGRO', 4985, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MICRONESIA', 4995, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MONTSERRAT', 5010, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('MOCAMBIQUE', 5053, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('NAMIBIA', 5070, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('NAURU', 5088, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CHRISTMAS', 5118, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('NEPAL', 5177, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('NICARAGUA', 5215, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('NIGER', 5258, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('NIGERIA', 5282, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('NIUE', 5312, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('NORFOLK', 5355, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('NORUEGA', 5380, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('NOVA CALEDONIA', 5428, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('PAPUA NOVA GUINE', 5452, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('NOVA ZELANDIA', 5487, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('VANUATU', 5517, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('OMA', 5568, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('PACIFICO', 5665, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('PAISES BAIXOS', 5738, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('PALAU', 5754, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('PAQUISTAO', 5762, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('PANAMA', 5800, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('PARAGUAI', 5860, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('PERU', 5894, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('PITCAIRN', 5932, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('POLINESIA FRANCESA', 5991, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('POLONIA', 6033, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('PORTUGAL', 6076, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('PORTO RICO', 6114, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('QUENIA', 6238, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('QUIRGUIZ', 6254, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('REINO UNIDO', 6289, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('REPUBLICA CENTRO-AFRICANA', 6408, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('REPUBLICA DOMINICANA', 6475, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('REUNIAO', 6602, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ZIMBABUE', 6653, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ROMENIA', 6700, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('RUANDA', 6750, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('RUSSIA', 6769, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SALOMAO', 6777, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SAARA OCIDENTAL', 6858, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('EL SALVADOR', 6874, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SAMOA', 6904, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SAMOA AMERICANA', 6912, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SAO CRISTOVAO E NEVES', 6955, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SAN MARINO', 6971, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SAO PEDRO E MIQUELON', 7005, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SAO VICENTE E GRANADINAS', 7056, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SANTA HELENA', 7102, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SANTA LUCIA', 7153, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SAO TOME E PRINCIPE', 7200, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SENEGAL', 7285, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SEYCHELLES', 7315, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SERRA LEOA', 7358, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SERVIA', 7370, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CINGAPURA', 7412, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SIRIA', 7447, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SOMALIA', 7480, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SRI LANKA', 7501, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SUAZILANDIA', 7544, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('AFRICA DO SUL', 7560, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SUDAO', 7595, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SUECIA', 7641, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SUICA', 7676, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('SURINAME', 7706, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('TADJIQUISTAO', 7722, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('TAILANDIA', 7765, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('TANZANIA', 7803, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('TERRITORIO BRIT.OC.INDICO', 7820, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('DJIBUTI', 7838, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CHADE', 7889, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('TCHECA', 7919, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('TIMOR LESTE', 7951, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('TOGO', 8001, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('TOQUELAU', 8052, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('TONGA', 8109, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('TRINIDAD E TOBAGO', 8150, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('TUNISIA', 8206, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('TURCAS E CAICOS', 8230, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('TURCOMENISTAO', 8249, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('TURQUIA', 8273, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('TUVALU', 8281, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('UCRANIA', 8311, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('UGANDA', 8338, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('URUGUAI', 8451, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('UZBEQUISTAO', 8478, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('VATICANO', 8486, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('VENEZUELA', 8508, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('VIETNA', 8583, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('VIRGENS (BRITANICAS)', 8630, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('VIRGENS (E.U.A.)', 8664, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('FIJI', 8702, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('WAKE', 8737, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('CONGO', 8885, 1);
INSERT INTO Países (Descrição, [Código do País], Inativo) Values('ZAMBIA', 8907, 1);

GO
